name             'foreman'
maintainer       'SalesLoft'
maintainer_email 'developers@salesloft.com'
license          'All rights reserved'
description      'Deploy foreman Procfiles as deploy/Procfile.[layer_short_name]'
version          '1.0.0'
